### PR TITLE
fix(firebase): update firebase dependency to fix grpc compilation error

### PR DESCRIPTION
**Pull request by saitodisse**
I've updated all cerebral version's here and now I'm getting @cerebral/firebase's npm install
error.

Only updated the firebase's dependencies

ISSUES CLOSED: #1365

### CODE REVIEW

**Comment by saitodisse** [comment]
I'm investigating why this tests are failing.

**Comment by christianalfoni** [comment]
You have time to look at the conflicts? Or I can make a copy if this branch and fix it, though then you loose the commit :-/

**Comment by christianalfoni** [comment]
Closing this

**Comment by saitodisse** [comment]
sorry @christianalfoni to not respond. Yes, it is better to remove firebase from cerebral, makes sense

**Pull request closed without merging**
