### PR TITLE
Fix typo in signals.md

### PR DESCRIPTION
**Pull request by evanblack**
Noticed a syntax typo while reading through the docs

### CODE REVIEW

**Comment by evanblack** [comment]
Not sure why the tests failed. I changed 1 line in 1 of the markdown files...

**Comment by evanblack** [comment]
Okay. This just seems like a really weird syntax for paths then  ¯\_(ツ)_/¯

**Comment by christianalfoni** [comment]
@evanblack Yeah, the function and the object is related by order :) It is the only way to express it declaratively with arrays and objects. Like we could wrap it:

```js
[
  paths(myAction, {
    success: [],
    error: []
  })
]
```

But it was chosen to do it by order to make it as declarative as possible. But can totally understand the syntax throws you off at first. Though you quickly get used to it and appreciate it being as clean as possible :)

Typically prettier cleans it up like this:

```js
[
  myAction,
  {
    success: [],
    error: []
  }
]
```

Which makes it more clear how the syntax works

**Comment by evanblack** [comment]
Thanks for the explanation! Makes sense!

**Pull request closed without merging**
