### PR TITLE
feat(Computed): simplify use of computed without props

### PR DESCRIPTION
**Pull request by gaspard**
```js
connect({
  foo: someComputed,
  foo2: someComputed.props({foo: 'bar'})
})
```

```js
function someAction({state}) {
  state.compute(someComputed)
  state.compute(someComputed.props({foo: 'bar'})
}
```

BREAKING CHANGE:

Use "myComputed" instead of "myComputed()"

### CODE REVIEW

**Comment by NervosaX** [comment]
They seemed fine before. What's the reason for the change?

Every breaking change is another reason upgrading to the next cerebral takes longer. Can handle both working? Or create a deprecation?

If there's a good reason, I'm not concerned. I just want to make sure we're not causing needless work to upgrade.

**Comment by gaspard** [comment]
As I understand it, the 2.0 release is the opportunity to clarify and sanitize API to make it easier for newcomers to get started and to reduce confusion. Not returning a factory as in 1.0 reduces the level of complexity. The goal is to have an API with least surprises and gotchas.

**Comment by gaspard** [comment]
@NervosaX There are lots fo breaking changes in 2.0 especially from pre 1.x (no more Baobab model, no immutable model, no support for snabbdom, totally different operators, etc). Could you give more details as to why this specific change does not seem valid compared to other changes ?

For reference: [list of changes from 1.x to 2.x](http://cerebral.github.io/cerebral-website/migration/01_start_migration.html)

**Comment by NervosaX** [comment]
Nope, simplicity is a good goal. I just would think handling the current method of computed functions would be just as easy to handle without forcing another upgrade collision.

**Comment by henri-hulski** [comment]
@NervosaX  I think in this case the upgrade is just a simple search and replace maybe with some regex.
We could even provide an upgrade script, which automates the upgrade as far as possible.

**Comment by NervosaX** [comment]
@henri-hulski: Agreed.

 I'm not attacking this change in particular, there's nothing wrong with it. I've been using cerebral for a good 8 months or so now, and upgrading has been a huge pain point (which is my problem, having used it before a 1.0 release).

I think an upgrade script is a great way to go about this.

**Comment by gaspard** [comment]
I thought about keeping the old method along the new one (by adding 'getValue' to the factory) but the only solutions I could come up with either involved passing the factory in places where a computed is expected and this did not look ideal or involved messing with the prototype (and this is also quite ugly). If there is a not too complex way to make an object (the computed) callable so that the old way still works we could use it... Any idea here very welcome... It could be used for deprecation without breaking (like in 1.99)...

**Comment by gaspard** [comment]
@NervosaX I also have a big app and the changes are hard (am waiting for 2.x, skipping 1.x altogether). We definitely need a good migration guide and some helper scripts if someone knows how to make them (and good demo apps I think). In my case, I also have to move from immutable+Snabbdom to React/Inferno (haven't decided yet) and Cerebral model. It's a pain but I really prefer how 2.x is becoming simpler and focussed.

I think there is a hangout planed.. Not sure. This should be discussed for sure.

**Comment by edgesoft** [comment]
@gaspard @NervosaX https://github.com/cerebral/cerebral/issues/318

**Comment by Guria** [comment]
I'll merge it at weekend then, if no more objections would be posted here.

**Comment by Guria** [comment]
I have also planned to make alpha release of all the things after this merged

**Comment by gaspard** [comment]
I will try to release the new operators tonight... Still got this question
on merge..

**Comment by Guria** [comment]
rebasing and merging now

**Pull request merged**
