### PR TITLE
feat(Operators): add support for multiple arguments to 'when'

### PR DESCRIPTION
**Pull request by gaspard**
Add support for these kind of things:

```js
when(state`clients.$draft.key`, input`key`, (a, b) => a === b), {
  // maybe update the form as well
}
```

### CODE REVIEW

**Comment by christianalfoni** [comment]
@gaspard Ah, yeah, this is very smart. Cause now you can do "&&" and "||" in the function there

**Comment by gaspard** [comment]
OK. Updating docs

**Comment by gaspard** [comment]
Sorry for the mess with website styles, will make another commit.

**Comment by gaspard** [comment]
OK. Updated docs (and solved my git-fu with working on website typo in parallel).

**Pull request merged**
