### PR TITLE
feat(router): add getSignalUrl back into router

### PR DESCRIPTION
**Pull request by idream3**
Using this feature throughout our app, it is needed for dynamic route display.

Usage:
```
const getUrl = controller.router.getSignalUrl;
```

### CODE REVIEW

**Comment by Guria** [comment]
Router would be updated to support new tags in 2.0. I am also plan to return getSignalUrl as well.

**Comment by idream3** [comment]
Thanks, sounds good. Do you have an ETA for 2.0?  I am upgrading our app to
Cerebral 2, but rely heavily on getSignalUrl.

**Comment by Guria** [comment]
@idream3 hope to update router on this week

**Comment by Guria** [comment]
Sorry about failed estimations. Now when computed stuff is about to lend it seems turn for router update

**Comment by edgesoft** [comment]
Think this is valid. If you use baseUrl you need to make you own function to support it so this is great.

**Pull request merged**
