### PR TITLE
feat(schemeParser): expose scheme parser from Cerebral

### PR DESCRIPTION
**Pull request by christianalfoni**
requires version of operators depending on scheme parser

### CODE REVIEW

**Comment by Guria** [comment]
@christianalfoni Error: Cannot find module 'cerebral-scheme-parser'

**Comment by christianalfoni** [comment]
Cause it needs the latest version of operators first :)

**Comment by Guria** [comment]
do you mean https://github.com/cerebral/cerebral-operators/pull/5 ?

**Comment by christianalfoni** [comment]
Jup, issue updated now

**Comment by Guria** [comment]
@christianalfoni rebase this pr on top of `next` branch and add depndency onto new operators package version when it ready

**Comment by Guria** [comment]
postponed to 2.0

**Pull request closed without merging**
