### PR TITLE
feat(forms): fixed default requiredMessage and global props factory example

### PR DESCRIPTION
**Pull request by yusufsafak**
Hi guys,
Form should be lowercase 
Related to cerebral/cerebral#462, you decided to keep global props outside the form. So I deleted this example and put it in factory. 
Thanks for the great library :)

### CODE REVIEW

**Comment by edgesoft** [comment]
@yusufsafak Great catch thanks! Just a question. Any reason MyAction is removed?

**Comment by henri-hulski** [comment]
@yusufsafak Nope. The decision was:

> We keep your snippet and change documentation to: "You can add any properties to a form where properties containing an object with a "value" property are identified as fields"...

So global props are allowed in the form.

**Comment by yusufsafak** [comment]
Himm I think I understood wrong this:

> We keep your snippet and change documentation to: "You can add any properties to a form where properties containing an object with a "value" property are identified as fields"...

**Comment by yusufsafak** [comment]
:) I will correct it now

**Comment by henri-hulski** [comment]
Yeah it's not really clear. Feel free to reformulate this sentence.

**Comment by henri-hulski** [comment]
@yusufsafak Sorry but you were actually right with removing the example. I forgot to clean it up. 
Like now it makes no sense. 
But I think I will restore it as it was before with a separate header as it is correct and I will also use it in the demo.

**Comment by henri-hulski** [comment]
@yusufsafak So thanks for catching this! ☺

**Pull request merged**
