### PR TITLE
task(test): Remove deprecated test function RunSignal 

### PR DESCRIPTION
**Pull request by garth**

### CODE REVIEW

**Comment by Guria** [comment]
what means **task** in commit message?

**Comment by garth** [comment]
A task is a item of work that has no user value.

**Comment by Guria** [comment]
But it still has user impact. it removes part of api. And we don't have `task` type in convention we use:
https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

**Comment by christianalfoni** [comment]
Where are we on this @Guria and @garth ?

**Comment by garth** [comment]
not sure, just wanted to remove the deprecated test fn before we hit 2.0, but I guess we are too late for that now.

**Comment by christianalfoni** [comment]
@Guria What changes do you require here?

**Comment by Guria** [comment]
I want that only supported commit types was used. For me here is a `feat(test):` with a breaking change section.

**Comment by henri-hulski** [comment]
I think this one should also be fixed and go in now.

**Comment by christianalfoni** [comment]
Moved to: https://github.com/cerebral/cerebral/pull/1100

**Pull request closed without merging**
