### PR TITLE
docs(tutorial): removed hashes from webpackbin-links

### PR DESCRIPTION
**Pull request by fopsdev**
removed hashes from the webpackbin links

### CODE REVIEW

**Comment by Guria** [comment]
conflicts :(

**Comment by fopsdev** [comment]
yeah meanwhile it's a bit outdated and simple to fix again :) , i will review the tutrial again when the seq() and par() - stuff possibly gets integrated. so feel free to delete this branch along with the other fopsdev-branches created when editing some website stuff directly

**Comment by Guria** [comment]
time to rebase?

**Comment by Guria** [comment]
outdated

**Pull request closed without merging**
