### PR TITLE
fix(Operators): operator when: throw errors for wrong input

### PR DESCRIPTION
**Pull request by reflog**
ISSUES CLOSED: #859

### CODE REVIEW

**Comment by Guria** [comment]
Great addition but doesn't covers my original case. It wasn't about path is not provided.
```js
[
  when(someTag === someTag). // wrong usage. must throw even if path true/false is defined
  {true: [], false: []} 
]
```

**Comment by reflog** [comment]
@Guria - so what exactly do you want to check? Right now stuff like `when(true)` already throws an error...

**Comment by Guria** [comment]
But what about `when(false), {true:[], false:[]}`? I think it eill fail due to my observations.

**Comment by reflog** [comment]
ok, i think this time I covered both cases

**Pull request merged**
