### PR TITLE
docs(tutorial): add tutorial as zip and point to new debugger page

### PR DESCRIPTION
**Pull request by christianalfoni**
Depends on : https://github.com/cerebral/cerebral/pull/482

### CODE REVIEW

**Comment by henri-hulski** [comment]
I would propose to use Github for the zip files. 
We can even put it in the root of the package and there should be a raw url to point to it. 

Alternatively we could create zips automatically in Github releases similar to the Atom downloads. 

But at least for now the former makes more sense.

**Comment by henri-hulski** [comment]
The URL would be something like 
https://raw.githubusercontent.com/cerebral/cerebral/master/packages/tutorial/tutorial.zip

**Comment by christianalfoni** [comment]
Yeah, github makes a lot more sense, totally agree. Let me change that :)

**Comment by christianalfoni** [comment]
Okay, this is updated now, will do the same for electron apps

**Comment by Guria** [comment]
No way. Let's avoid artifacts under vcs

**Comment by christianalfoni** [comment]
@Guria I am completely blank on this... not sure what is best approach. You have any idea of where we can/should store it? :)

**Pull request closed without merging**
