### PR TITLE
feat(state): add toggle mutation

### PR DESCRIPTION
**Pull request by sveint**
Adds toggle mutation to state for convenience.

### CODE REVIEW

**Comment by gaspard** [comment]
Hi @sveint nice work. Could you also change `toggle` operator so that it uses this new method in state for consistency ?

https://github.com/cerebral/cerebral/blob/master/packages/cerebral/src/operators/toggle.js

**Comment by sveint** [comment]
Good point! Changed it now.

**Comment by Guria** [comment]
Also would be great to see it in operators documentation

**Comment by sveint** [comment]
@Guria Since the `toggle` operator was added previously be someone else, it's already there. See http://cerebraljs.com/docs/api/operators.html#toggle . Or did you refer to something else?

**Comment by edgesoft** [comment]
@sveint Think he means here http://cerebraljs.com/docs/api/state.html

**Comment by sveint** [comment]
@edgesoft That should already be covered in this pull request.

**Comment by Guria** [comment]
Ahh. I see now.

**Comment by sveint** [comment]
Thank you :-)

**Pull request merged**
