### PR TITLE
fix(Computed): find computedRef with underscores in the cache

### PR DESCRIPTION
**Pull request by garth**
#209

### CODE REVIEW

**Comment by Guria** [comment]
LGTM

**Comment by Guria** [comment]
You can push to master the same commit now. Or you will wait @christianalfoni ?

**Comment by garth** [comment]
I think that Christian can merge if he likes it. I can do a find and replace at my end for _ until then.

**Comment by christianalfoni** [comment]
Oh! YEah, sorry, bad implementation by me :-)

**Comment by christianalfoni** [comment]
mmm... , how do I get it into master? :-)

**Comment by Guria** [comment]
@christianalfoni I will help with it a little bit later

**Comment by Guria** [comment]
@christianalfoni Outside pr's is most tricky here :(
There is several ways to do it. If we want to PR correctly marked as merged we should ask @garth to make rebase and force push to the same branch in his repo. Since @garth has push rights he can also push it to this repo master after travis gives ok.

But things complicates if pr author can't do rebase. You'll have to get his changes (by adding fork as remote or [using hub utility](https://hub.github.com/#maintainer)) make rebase on your own and push to repo so travis could check it and push to master after. The drawback here is that pr will not be merged automatically since commit hash will not be the same as PR's one.

**Comment by christianalfoni** [comment]
Okay, given @garth write permission to repo. Let me know if I need to get back in here :) Though seems more complicated form my end?

**Comment by Guria** [comment]
moved to pre-0.34 branch

**Pull request closed without merging**
