### PR TITLE
chore: move to prettier, use lint-stage to auto fix files before commit

### PR DESCRIPTION
**Pull request by reflog**
ISSUES CLOSED: #732

### CODE REVIEW

**Comment by reflog** [comment]
I know this commit is noisy, there are differences in style between prettier and what we had, but I think it'll be very good in the long run. What are your thoughts? Also, lint-staged approach is better than pre-test, since it avoids bad commits.

**Comment by henri-hulski** [comment]
@reflog Could you split the PR in 2 commits?
One with your changes and one with the refactor by prettier?
Like this it's impossible to review.

**Comment by reflog** [comment]
done.

**Comment by henri-hulski** [comment]
Don't think we need prettier-standard as prettier supports now semi option.
When using prettier directly we will have a more recent version.
We should also discuss which options to use.
I'm using
```json
{
  "trailingComma": "es5",
  "singleQuote": true,
  "bracketSpacing": false,
  "semi": false
}
```
The last 3 makes it similar to standard but the first is not in standard.
But it makes diffs more readable (no lines which only changes trailing commas)
and also easier to copy/paste parts of arrays/objects (no need to add/remove trailing commas).

**Comment by reflog** [comment]
@henri-hulski - didn't know prettier now has semi option... good! about 'recent' issue - it's not a problem, prettier-standard uses peerDependency, so we can add prettier of any version ourselves.
Regarding specific style - that's for the core team to decide I suppose, I'm good with any solution, as long as it's enforced by the tooling :)

**Comment by Guria** [comment]
Good point. Agree with you.

**Comment by reflog** [comment]
👌

**Comment by Guria** [comment]
@reflog I will close it now since it would make no sense to rebase it over comming changes.

Btw, would be great to have separate commit for configuration changes and another commit for applied changes from prettier.

Also make sure to check https://github.com/feross/standard/issues/811 before next attempt please.

**Pull request closed without merging**
