### PR TITLE
WIP: Improved typings DO NOT MERGE: commits moved to #1055

### PR DESCRIPTION
**Pull request by nd0ut**
Hello! I decided to make some improvements of the typescript declarations.

- types for base cerebral entities (actions, signals, computed, context) to make autocomplete work and make the code more understandable
- more strict type checking (change return and acceptable types) 
- doc page with usage examples

I'll happy seeing your comments and suggestions.

### CODE REVIEW

**Comment by gaspard** [comment]
Nice work @nd0ut ! I checked out the types and will add my own work on generic types for connect and maybe also ActionContext on top of this PR later today. 👍

**Comment by Guria** [comment]
@nd0ut Great job, thx. Would be great to see tests for this stuff.

**Comment by gaspard** [comment]
Now working on #1055 (local branch). I added generic types and fixed/tested in my (complex) TypeScript app and they work fine.

**Comment by gaspard** [comment]
@nd0ut if you want to commit other changes, please fork "nd0ut" branch and add changes on top of this or add them here and I will rebase "nd0ut" branch on top of this.

**Pull request closed without merging**
