### PR TITLE
docs(tutorial): fix broken links for deeper study

### PR DESCRIPTION
**Pull request by ejhessing**
Hello, When I went through the tutorial I found some broken links and hence figured I'd help fix them.

### CODE REVIEW

**Comment by Guria** [comment]
Hi. Thanks for your help. PR with new documentation is about to land soon #624.
Could you checkout a next branch with suggested fixes?

**Comment by Guria** [comment]
Please revisit new docs in master and chaeck if any edits still necessary

**Comment by ejhessing** [comment]
Hi, sorry been a little busy, will look at it this weekend and make changes if needed.

**Comment by ejhessing** [comment]
Hi Guria, The changes have seem to be already fixed in the new tutorial.  Cheers and keep up the great work!  
Thanks, 
Erwin

**Pull request closed without merging**
