### PR TITLE
docs(website): add standalone debugger downloads

### PR DESCRIPTION
**Pull request by christianalfoni**
Okay, got them built and uploaded to Google Drive for now... completely open to put them somewhere else :) But at least now people can try it out!

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hm... we could have these on github as well, though they are 40MB each. Meaning the install of monorepo would be very large.

Maybe create a separate repo for this? Or any other ideas?

**Comment by henri-hulski** [comment]
Yeah this is the caveat I thought about. If it's so big no way to put it in the repo. 
The best would be to add it as a binary file to the release. In the meantime either leave it on Google or create a separate repo.

**Comment by henri-hulski** [comment]
Maybe the easiest would be to just make a preview release for each every  new version of the debugger. 
Not sure if there will be a permanent url but otherwise we can add an URL to a redirect on the website.

**Comment by Guria** [comment]
Github releases supports to attach binaries

**Comment by Guria** [comment]
Just downloaded debugger and have several questions:
* "Please refresh your app to use the debugger..." is completely useless. We should provide better instructions here.
* which port does it starts? can it be configured? 8080 is not a good choice for default port.
* what will happen when several instances and/or apps will connect to the same debugger host?

**Comment by henri-hulski** [comment]
@Guria Yep, but if I'm not mistaken every release will have a different URL. So to have a permanent URL we need a redirect somewhere so it's easier to bookmark. 
But not really sure if this is necessary.

**Comment by Guria** [comment]
@henri-hulski https://github.com/cerebral/cerebral/releases/latest is pretty permanent

**Comment by Guria** [comment]
I will merge this for now, but we must address issues described above

**Comment by henri-hulski** [comment]
@Guria Aah cool. So something like 
https://github.com/cerebral/cerebral/releases/download/latest/tutorial.zip

**Comment by christianalfoni** [comment]
@Guria @henri-hulski Okay, so we can attach debugger to repo somehow? How will this work? And we need to version them.

@Guria I will address the issues you stated, completely agree :)

**Comment by henri-hulski** [comment]
@christianalfoni Take a look what @Guria did [here](https://github.com/cerebral/cerebral/releases/tag/untagged-e5b773432376958077d1).

**Comment by christianalfoni** [comment]
Oh... cool... how did you do that @Guria ?

**Pull request merged**
