### PR TITLE
feat(UniversalController): allow multiple runs of Signals.

### PR DESCRIPTION
**Pull request by sladiri**
Add an option to skip runOnce check in UniversalController.

### CODE REVIEW

**Comment by christianalfoni** [comment]
@sladiri I suggest we allow multiple runs by default. We rather set `hasRun` to `true` when `getScript()` is called.... meaning that there is no reason to update the controller anymore. What you think? :)

**Comment by sladiri** [comment]
@christianalfoni OK, I was cautious in case you might want to keep the old default behavior. It works for me so far. :)

**Comment by sladiri** [comment]
@christianalfoni Do you require that the coverage is at least the same, should I add tests to increase it? I did not want to add a test just for the sake of better coverage.

**Comment by sladiri** [comment]
I botched a test before, it ran just one signal (`should allow multiple runs`). Fixed it now.

**Pull request merged**
