### PR TITLE
chore(tests): collocate tests with sources

### PR DESCRIPTION
**Pull request by gaspard**
ISSUES CLOSED: #338

### CODE REVIEW

**Comment by Guria** [comment]
@gaspard btw you should have a rights to push a new branch for pr right in this repo

**Comment by gaspard** [comment]
Regarding `require`, I just changed the paths from `../src/operators/something` to `./something` without adding new lines (least code changes): they were already all over the place.

Concerning pushing a branch for pull request, you mean I create a branch in my `cerebral/cerebral.git` repo and push it to origin and then do a pr ?

**Comment by Guria** [comment]
> they were already all over the place

I noted it. That's why I mentioned @christianalfoni 

> Concerning pushing a branch for pull request, you mean I create a branch in my cerebral/cerebral.git repo and push it to origin and then do a pr ?

Yes. You can just clone from this repo and have it as origin. Then you just starts a local branch and when it is ready you just pushes it back using `git push origin`

**Comment by gaspard** [comment]
:-) Thanks @Guria

**Pull request merged**
