### PR TITLE
refactor(website): integrate cerebral-website into monorepo

### PR DESCRIPTION
**Pull request by henri-hulski**
Related to #398

### CODE REVIEW

**Comment by Guria** [comment]
hmm, somehow you have imported previous website as well. There shouldn't be app and server folders.

**Comment by Guria** [comment]
v3 branch contains only 93 commits and it doesn' contains previous website at all. but this pr contains 250+ commits including previous website.

**Comment by henri-hulski** [comment]
Yeah I have merged it in master first. 
So the branch is self contained right? 
I will do it again without merging. 

I think I did something similar with cerebral-module-useragent. I hope there it's ok.

**Comment by Guria** [comment]
No problems with useragent. There was branches with shared parents.
But website v3 started as orphan branch.
Also don't forget to include lint fixes

**Comment by henri-hulski** [comment]
@Guria Should be fixed now.

**Pull request merged**
