### PR TITLE
fix(router): preserve the default state value

### PR DESCRIPTION
**Pull request by hipertracker**
Fix the problem reported at https://github.com/cerebral/cerebral/issues/1244. The original code always set the default state value to null.

### CODE REVIEW

**Comment by Guria** [comment]
Great. Could we add a test to cover this case?

**Comment by Guria** [comment]
Hmm, does url updated with value from store?

**Comment by hipertracker** [comment]
Yes, the url is updated with the default value from store, but I cannot create a unit test to prove it. 

I have created another unit test showing for preserving the default state but how to amend it to this commit at Github?

**Comment by Guria** [comment]
Just make a push from clone of your forked repo to patch-11 branch.

**Comment by henri-hulski** [comment]
You have to do it from your local machine using git:
```sh
git clone git@github.com:hipertracker/cerebral.git
git checkout patch-11
```
Then you can eit amend to your commit or add new commits. When pushing it to the server (when amending you need a force push) it will be automatically added to the PR.
```sh
git push [--force]
```
Remember also to use `npm run commit` instead of `git commit` as this helps you to use the schema for the commit message which is after used for creating the release notes.
Otherwise we have to change your commit message later. 
```sh
git add .
npm run commit
```

**Comment by henri-hulski** [comment]
Sorry I was hitting the wrong button. :-)

**Comment by hipertracker** [comment]
Sorry, I send the "amend" and "push" commands with Tower git client instead of the terminal. The commit title has to be changed.

**Comment by henri-hulski** [comment]
The PR should be rebased as it contains commits which are already merged but the commit message was adjusted afterwards.

**Pull request merged**
