### PR TITLE
feat(forms): add new initializeForm factory and nested form tests

### PR DESCRIPTION
**Pull request by yusufsafak**

### CODE REVIEW

**Comment by henri-hulski** [comment]
Looks great! Just some linting must be fixed.

**Comment by henri-hulski** [comment]
And documentation of initializeForm is missing.

**Comment by yusufsafak** [comment]
Thanks for review. I fixed lint errors and add documentation of initializeForm :)

**Comment by henri-hulski** [comment]
Are you sure that you need here
```js
        newField.defaultValue = newInitialValues || newField.defaultValue
        newField.value = newField.defaultValue
        newForm[key] = configureField(form, newField)
```
as in configureField we have
```js
  const value = field.value
  const defaultValue = field.defaultValue || value
```
Which looks more or less the same.

**Comment by henri-hulski** [comment]
But ok maybe it makes sense.
I think the PR looks ready now.

**Pull request merged**
