### PR TITLE
feat(Operators): improve support for compute in operators (when, equals)

### PR DESCRIPTION
**Pull request by maxfrigge**

### CODE REVIEW

**Comment by Guria** [comment]
@christianalfoni please review

**Comment by maxfrigge** [comment]
@christianalfoni I have refactored and rebased. When you say add docs, are you talking about `canResolve` in general or samples where computed is used with `when` or `equals`?

**Comment by christianalfoni** [comment]
Both @maxfrigge , would be great :-)

**Comment by Guria** [comment]
Probably needs revisiting now #1121 is merged

**Comment by christianalfoni** [comment]
Closing this, you are just taking too long @maxfrigge ;-) But yeah, this should be put into function-tree now

**Pull request closed without merging**
