### PR TITLE
feat(firebase): add google signin

### PR DESCRIPTION
**Pull request by christianalfoni**

### CODE REVIEW

**Comment by henri-hulski** [comment]
@christianalfoni Are you planning to add Github signin too? 
For example for the demo as it's for developers.

**Comment by christianalfoni** [comment]
@henri-hulski Feel free to add it :)

**Comment by henri-hulski** [comment]
@christianalfoni Ok I will put it on my list.  :)

**Comment by henri-hulski** [comment]
@christianalfoni Is there a reason why you didn't add `signInWithGoogle` to `context.firebase`?

**Comment by christianalfoni** [comment]
Ah, crap... I missed it, will make another pull. Thanks @henri-hulski :)

**Pull request merged**
