### PR TITLE
WIP: Debugger autoupdate

### PR DESCRIPTION
**Pull request by reflog**
Hi guys.
I've added the code needed to implemented the installer and auto-update for CerebralJS debugger.
First of all, I've replaced electron-packager with electron-builder and included the electron-autoupdate module.
Also, per electron-builder docs - icons are moved into build/ folder.

The suggested procedure for releases is described here:
https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

The process is very simple:
1. Create some new code
2. Build the release either with Appveyor or Travis or locally on target machine (no cross-compilation is possible, so you need build machine per target Win/Mac/Linux) using `npm run build`
3. Draft a release, tag, etc, upload the binaries (It supports Github tokens and release mechanism, take a look at the link above).
4. On start, auto updater will query Github releases list and will notify the user if new release is available.

I've also added rather extensive logging for auto-update, feel free to remove them.

### CODE REVIEW

**Comment by reflog** [comment]
oh, and one more thing, I've left the build {} section in package.json rather sparse, since I didn't want to populate it with incorrect values

**Comment by henri-hulski** [comment]
@reflog I think with electron-builder it would also be easy to create deb packages.

**Comment by reflog** [comment]
Absolutely. electron-builder supports that too. But again - you will need a separate build machine setup.

**Comment by henri-hulski** [comment]
It seems that you can also build for Linux and Windows on MacOS:
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#macos
Or you can trigger the builds for Linux and MacOS with Travis.

**Comment by christianalfoni** [comment]
This is awesome @reflog :) I wonder how you sign the build for Mac on Travis though.. now I sign it manually on my local machine, hm

**Comment by christianalfoni** [comment]
@Guria I guess you have some feedback here as well? :)

**Comment by reflog** [comment]
Sorry - but Mac is out of my scope. I'm Linux and Windows guy, I can help getting the builds running there :)

**Comment by christianalfoni** [comment]
@reflog Ah, I see, so `electron-builder` is environment specific? So Travis somehow needs to fire up the build on the specific environments? I guess it needs a separate service for that? As Travis is only linux?

**Comment by reflog** [comment]
from the docs: 
" (since AppVeyor can build only Windows and Travis only macOS / Linux). "
so I guess the best way would be to add two commands to package.json and run one on Appveyor and one on Travis and get 3 results.

**Comment by christianalfoni** [comment]
Cool, I see, hm... lets get @Guria in here to plan this out with current publishing routines

**Comment by reflog** [comment]
Great. Well, if I can help with anything - please ping me

**Comment by henri-hulski** [comment]
Here is an example [.travis.yml](https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml). 
On the other hand [they say](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build) 
> macOS Code Signing works only on macOS. Cannot be fixed.

But maybe Travis can be run on MacOS.

**Comment by christianalfoni** [comment]
@reflog I am eager to get this in place :) Maybe we should create a test repo and electron app with travis where we try this out? So that we have a clear description for @Guria? I can set it up if you agree :)

**Comment by reflog** [comment]
@christianalfoni - sounds great, let's try that out!

**Comment by christianalfoni** [comment]
hmmm... I have been looking into this and to me this looks seriously complex:

1. Configuring Travis
2. Travis can not build windows, so need own handling of that
3. Hook it up to Github
4. Add windows installer for auto update to work on windows (Is required)
5. How do we sign Mac apps on Travis? It requires a certificate
6. Implement handling of Cerebral version support, so it does not update when you have a conflicting Cerebral version

To me now I really do no want this to be a blocker. I think we should just do:

1. Download package.json of debugger with XmlHttpRequest in Github. Check version against current version. If new version, show popup with link to debugger website
2. On debugger website we list versions and you download it manually. It states from which Cerebral version it supports

This will take one person one day to implement, rather than having extra work on @Guria , who needs to figure out just publishing the lib itself and tons of research making this auto update work on all platforms.

Like... I would love to have it, but I just do not see it as being a realistic thing to do before release without it being delayed a lot. So I think we should do the simple way for release, to not cause any delays, and then we can put effort into making this completely automatic after release :)

**Comment by reflog** [comment]
I understand your hesitation... We can do what you suggest as a first step, to clean this off the plate for 2.0.
I'll be glad to implement this basic update-check.

**Comment by christianalfoni** [comment]
@reflog You know, I hate taking away any enthusiasm here. I suggest this:

I will implement the simple version now and please keep working on this and grab my attention whenever needed. I just want to make sure we have something that does not block release first. If we get this approach up and running before any other blockers that is awesome and I will cheer this approach, cause it really is supercool :-)

**Comment by reflog** [comment]
👍  I think I'll set up my own copy of cerebral repo, travis and appveyor, configure everything, see that it actually works and then do a write-up on how to get it all together. Because from the code-standpoint, everything is ready, all we need is the infrastructure setup.

**Comment by christianalfoni** [comment]
@reflog Sounds awesome! :) I am a bit edgy these days on things that might block release, so sorry if I was discouraging! I think this writeup of yours can be super useful for other projects as well I would believe! :)

**Comment by reflog** [comment]
Not discouraging at all. I want C2 to be released to wider audience as well! And it's a good idea, I might make a blog post of it :)

**Comment by Guria** [comment]
@christianalfoni electron app could be build on linux machine with wine as I remember. I have done in on my cloud9 machine.

**Comment by Guria** [comment]
But I am ok with your first step suggestion.

**Comment by Guria** [comment]
So where we are here now? Is it still valid or we have some drastic changes here?

**Comment by reflog** [comment]
I think you can close this PR, since the actual work on fully working autoupdate with Travis builds, etc is right now in my own fork. And for now, @christianalfoni decided to include only his basic update mechanism for the C2 release.

**Pull request closed without merging**
