### PR TITLE
publish es modules

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by Guria** [comment]
Implemented es modules for rollup/broccoli support. Based on redux-saga repo.

**Comment by Guria** [comment]
will add more packages soon

**Comment by christianalfoni** [comment]
@Guria You want this to be WIP? Or pull in as we go?

**Comment by Guria** [comment]
Have to rebase it now.
Probably I need a small pause between releases to introduce it for main packages at least.

**Comment by Guria** [comment]
ok, it is ready here for 2 main packages

**Pull request merged**
