### PR TITLE
Integrate cerebral-provider-http in Monorepo

### PR DESCRIPTION
**Pull request by henri-hulski**
Related to #351

### CODE REVIEW

**Comment by Guria** [comment]
linting failed

**Comment by henri-hulski** [comment]
Yeah just fixed most of them. Don't know, how to fix the remaining.
```
standard: Use JavaScript Standard Style (http://standardjs.com)
  cerebral-provider-http/src/fileUpload.js:21:18: 'XMLHttpRequest' is not defined.
  cerebral-provider-http/src/fileUpload.js:34:38: 'FileList' is not defined.
  cerebral-provider-http/src/fileUpload.js:34:83: 'File' is not defined.
  cerebral-provider-http/src/fileUpload.js:35:28: 'FormData' is not defined.
  cerebral-provider-http/src/fileUpload.js:37:30: 'FileList' is not defined.
  cerebral-provider-http/src/index.js:7:5: 'allowedContentTypes' is defined but never used.
  cerebral-provider-http/src/request.js:2:17: 'XMLHttpRequest' is not defined.
```

**Comment by henri-hulski** [comment]
@christianalfoni Do you need 'allowedContentTypes' in index.js?
At the moment it's not used.
'XMLHttpRequest', 'FileList', 'File' and 'FormData' are not defined. Not sure what to do with that.

**Comment by Guria** [comment]
@henri-hulski 
just add a comment at the top of fileUpload.js and request.js
```js
/* eslint-env browser */
```

**Comment by christianalfoni** [comment]
@henri-hulski No, do not need anymore. I thought client had some saying in cross site requests, but it turns out to be only server side. The only thing client can decide is to pass cookies or not, which is `withCredentials` options :)

**Comment by henri-hulski** [comment]
@Guria linting passing now. Ready for review.

**Comment by Guria** [comment]
Another great job. Thanks

**Pull request merged**
