### PR TITLE
docs: fix link to function-tree

### PR DESCRIPTION
**Pull request by jdreesen**

### CODE REVIEW

**Comment by jdreesen** [comment]
I noticed there are some more broken links, e.g. 
- "[Install Cerebral](http://cerebraljs.com/docs/resources/01_cerebral.html)" on http://cerebraljs.com/docs/resources/boilerplates.html
- "[the tutorial](http://cerebraljs.com/docs/developer_guide/index.html)" on http://cerebraljs.com/docs/introduction/install.html

But I'm not sure what the correct links would be for these.

**Comment by christianalfoni** [comment]
@jdreesen 

1. http://cerebraljs.com/docs/introduction/install.html

2. http://cerebraljs.com/docs/introduction/state.html

:)

**Comment by henri-hulski** [comment]
2. http://cerebraljs.com/docs/introduction/state.html#tutorial :)

**Comment by jdreesen** [comment]
Great, pull request incoming!

**Pull request merged**
