### PR TITLE
fix(firebase): fix firebase signal callbacks (was using old api)

### PR DESCRIPTION
**Pull request by gaspard**

### CODE REVIEW

**Comment by gaspard** [comment]
@christianalfoni "createOnChildAdded" no longer needs to be a factory since "controller" argument is not used. I'll clean this up and push the new changes.

**Comment by gaspard** [comment]
I tested with demo and all works fine now (including file upload).

**Comment by christianalfoni** [comment]
@gaspard Does this change require you to use tags inside actions?

```js
function someAction ({firebase}) {
  return firebase.onValue('some.path', signal`woop`)
}
```

?

**Comment by gaspard** [comment]
@christianalfoni Yes.

I understand that we have to either expose two providers, one for operators and the other one for actions or simply use tags in actions.

Discussion continued on discord...

**Comment by Guria** [comment]
@christianalfoni so what resolution on this one?

**Comment by christianalfoni** [comment]
@gaspard Was this one updated after talk on Discord? :)

**Comment by gaspard** [comment]
@christianalfoni Sorry for the delay. Haven't had much time to code. Will do this "operators" export today.

I will also make sure the regular provider does contain any Tag supporting code. I think you are right, if things are to be separated, they have to be so completely.

**Comment by gaspard** [comment]
Will create a new pull request.

**Pull request closed without merging**
