### PR TITLE
fix(errors): don't throw exceptions when listeners attached to signalError

### PR DESCRIPTION
**Pull request by jeroenverfallie**
Straight forward.

See docs for the boolean: https://nodejs.org/api/events.html#events_emitter_emit_event_arg1_arg2

### CODE REVIEW

**Comment by jeroenverfallie** [comment]
This does of course mean that you are responsible for handeling the exception, as otherwise it's suppressed.

But I believe it makes sense you can catch it, otherwise the event is missing its use.

**Comment by jeroenverfallie** [comment]
Did the same for the normal `error` listener, and changed `const` to `var`.. sorry.. habits.

**Comment by Guria** [comment]
@jeroenverfallie could be it also tested?

**Comment by Guria** [comment]
@jeroenverfallie please squash commits and use `signalFactory` as scope in message:
```js
git rebase @~2 -i # follow instructions to mark commits to squash, save and exit
git push -f # force push to your fork
```

**Comment by jeroenverfallie** [comment]
Will do..

@christianalfoni any reason for https://github.com/cerebral/cerebral/blob/master/src/CreateSignalFactory.js#L174 
to be different to 
https://github.com/cerebral/cerebral/blob/master/src/CreateSignalFactory.js#L258

Is it used in the debugger?

**Comment by jeroenverfallie** [comment]
Had to use a try catch instead of asserts throws, because I had no way of knowing when the signal ended, because signalEnd doesn't reach, nor could I attach to signalError for testing purposes :)

**Comment by jeroenverfallie** [comment]
After really thinking this through, this is not the way to go as you do want your state to update with errors, and update the UI, thus breaking a signal doesn't work, obviously. 

Closing until there's a better solution.

**Pull request closed without merging**
