### PR TITLE
feat(inferno): update to latest version of inferno(v4)

### PR DESCRIPTION
**Pull request by aguilera51284**

### CODE REVIEW

**Comment by henri-hulski** [comment]
Hmm, should the commit message not be "move inferno from 3.x to 4.x"?
If you want to fix it you can do
```sh
$ git commit --amend  # fix the message
$ git push --force
```

**Comment by aguilera51284** [comment]
could be "feat(inferno): update to latest version of inferno(v4)"?

**Comment by henri-hulski** [comment]
Sounds good.

**Comment by henri-hulski** [comment]
Moved to #1273.

**Pull request closed without merging**
