### PR TITLE
feat: remove input and output validation

### LINKED ISSUE #260: Remove type checking
It would simplify that action implementation to remove [typechecking](http://www.cerebraljs.com/utilities/typechecking) from action input and outputs.

If we did this, you could still type check your actions by using an external library like tcomb. 

Does anyone have any use cases/reasons for keeping action type checking in cerebral? If not, we should work on removing it.

### PR DESCRIPTION
**Pull request by maxfrigge**
Fixes #260

### CODE REVIEW

**Comment by maxfrigge** [comment]
Don't merge yet. We should create a deprecation warning and transform objects into arrays for output defintions. Otherwise it will break to many projects.

**Comment by TomKaltz** [comment]
Is this for performance?

On Sunday, July 3, 2016, maxfrigge <notifications@github.com> wrote:

> Don't merge yet. We should create a deprecation warning and transform
> objects into arrays for output defintions. Otherwise it will break to many
> projects.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cerebral/cerebral/pull/264#issuecomment-230154114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC0_ISVmH3UvcfrgeFSh4MKDPEbE8W-Yks5qR7xZgaJpZM4JD19C>
> .
>


-- 
Thomas Kaltz III
586-214-7150
Sent from Gmail Mobile

**Comment by saulshanabrook** [comment]
@TomKaltz No, just to keep things simpler and reduce the scope of the core. The consensus seemed to be that if you want this type of safety, something like tcomb would probably be more useful for you.

It is also related to a larger goal of moving hopefully to typescript, which would give use some similar safety, but at compile time.

Do you have a preference for keeping these types?

**Comment by TomKaltz** [comment]
I don't use them.  No preference.

On Sunday, July 3, 2016, Saul Shanabrook <notifications@github.com> wrote:

> @TomKaltz <https://github.com/TomKaltz> No, just to keep things simpler
> and reduce the scope of the core. The consensus seemed to be that if you
> want this type of safety, something like tcomb would probably be more
> useful for you.
>
> It is also related to a larger goal of moving hopefully to typescript,
> which would give use some similar safety, but at compile time.
>
> Do you have a preference for keeping these types?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cerebral/cerebral/pull/264#issuecomment-230166082>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC0_IW3OFHMy-K3SKeUBfh9e1rZ2VS9sks5qR_cvgaJpZM4JD19C>
> .
>


-- 
Thomas Kaltz III
586-214-7150
Sent from Gmail Mobile

**Comment by Guria** [comment]
I think we should rebase this pr over "state-tree" branch to include it in 0.35 major release

**Comment by Guria** [comment]
@christianalfoni lot af unrelated changes in commit. can't get actual ones :(

**Comment by Guria** [comment]
much better now, thanks

**Pull request merged**
