### PR TITLE
feat(firebase-admin): added listUsers

### PR DESCRIPTION
**Pull request by tomhah**
Added listUsers function from firebase-admin and updated the firebase-admin npm package

### CODE REVIEW

**Comment by henri-hulski** [comment]
I see that now the commit history gets a little mixed up.
It would also be good to merge the 2 PRs as otherwise they will conflict. 

So I think the easiest would be to close this one and add a second commit to #1191 for listUsers.

**Comment by henri-hulski** [comment]
Here is a conflict with the base branch. Could you rebase?
There should also be only 2 commits here.

**Comment by christianalfoni** [comment]
@henri-hulski How exactly to solve this? Just rebase?

**Comment by henri-hulski** [comment]
@christianalfoni Not sure what happened here. My first proposition was to close this one and add the `feat(firebase-admin): added listUsers` commit to #1191.
This should be straightforward.

**Comment by christianalfoni** [comment]
Just created new PR, sorry @tomhah, too much git 💩 Moved it here: https://github.com/cerebral/cerebral/pull/1198

**Pull request closed without merging**
