### PR TITLE
Computed factories

### PR DESCRIPTION
**Pull request by Guria**
we can create a pr to make reviews

### CODE REVIEW

**Comment by Guria** [comment]
you have one extra commit, which is better to avoid. you shouldn't merge `master` to `feature-branch`, but run `git rebase master` to actualize feature-branch

**Comment by Guria** [comment]
now you should run
```sh
git rebase @~2 -i # nano would be bring, just remove line with merge commit, save and exit
git rebase origin/master # rebase feature-branch on top of master
git push origin computed-factories - f # force push to feature-branch to update pr
```

**Comment by Guria** [comment]
Then you have to wait until travis finish to check pr. But today travis is slow as hell.

**Comment by christianalfoni** [comment]
Okay, cool! I need @garth url scheme compiler as well. Moving it into its own repo with same configuration as addons. So that will take some time :)

**Comment by Guria** [comment]
tests are done

**Comment by Guria** [comment]
maybe we should batch some prs into one push, since travis is slow

**Pull request merged**
