### PR TITLE
refactor(website): simplify and improve clarity of menu code

### PR DESCRIPTION
**Pull request by bdjnk**
In order fix various small visual niggles in the menu it was necessary to refactor the menu css
significantly and the js code somewhat as well.

### CODE REVIEW

**Comment by henri-hulski** [comment]
@bdjnk could you rebase?
@gaspard made some changes in #1157.

**Comment by bdjnk** [comment]
@henri-hulski Merge, or truly rebase, then what, force push? Seems like risky business.

**Comment by henri-hulski** [comment]
@bdjnk Rebase and force push is okay for PR branch. 
That is what we do most time. ;) 
And resolve conflicts.

**Comment by bdjnk** [comment]
I've managed to get git into a somewhat fun state, as you can see (particularly if you look at the reflog). The code should be fine at least. @henri-hulski @christianalfoni

**Pull request merged**
